//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 12:53:29 PM CDT 
//


package bancoppel.cliente3.schema.SpConsultaDatosCteCoppel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpConsultaDatosCteCoppelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsultaDatosCteCoppelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cabecera" type="{http://www.bancoppel.com/Logger}CabeceraType"/>
 *         &lt;element name="numCte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsultaDatosCteCoppelType", propOrder = {
    "cabecera",
    "numCte"
})
public class SpConsultaDatosCteCoppelType {

    @XmlElement(required = true)
    protected CabeceraType cabecera;
    protected String numCte;

    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link CabeceraType }
     *     
     */
    public CabeceraType getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabeceraType }
     *     
     */
    public void setCabecera(CabeceraType value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the numCte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCte() {
        return numCte;
    }

    /**
     * Sets the value of the numCte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCte(String value) {
        this.numCte = value;
    }

}
