//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 12:53:29 PM CDT 
//


package bancoppel.cliente3.schema.SpConsultaDatosCteCoppel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpConsultaDatosCteCoppelRegistroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsultaDatosCteCoppelRegistroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cCodRet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cIngresoMensual" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cOpcionPuesto" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cSubOpcionPuesto" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cTiempoEdoCivil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cTiempoRecide" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cTipoRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsultaDatosCteCoppelRegistroType", propOrder = {
    "cCodRet",
    "cIngresoMensual",
    "cOpcionPuesto",
    "cSubOpcionPuesto",
    "cTiempoEdoCivil",
    "cTiempoRecide",
    "cTipoRef"
})
public class SpConsultaDatosCteCoppelRegistroType {

    protected String cCodRet;
    protected Integer cIngresoMensual;
    protected Integer cOpcionPuesto;
    protected Integer cSubOpcionPuesto;
    protected String cTiempoEdoCivil;
    protected String cTiempoRecide;
    protected String cTipoRef;

    /**
     * Gets the value of the cCodRet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCodRet() {
        return cCodRet;
    }

    /**
     * Sets the value of the cCodRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCodRet(String value) {
        this.cCodRet = value;
    }

    /**
     * Gets the value of the cIngresoMensual property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCIngresoMensual() {
        return cIngresoMensual;
    }

    /**
     * Sets the value of the cIngresoMensual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCIngresoMensual(Integer value) {
        this.cIngresoMensual = value;
    }

    /**
     * Gets the value of the cOpcionPuesto property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCOpcionPuesto() {
        return cOpcionPuesto;
    }

    /**
     * Sets the value of the cOpcionPuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCOpcionPuesto(Integer value) {
        this.cOpcionPuesto = value;
    }

    /**
     * Gets the value of the cSubOpcionPuesto property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCSubOpcionPuesto() {
        return cSubOpcionPuesto;
    }

    /**
     * Sets the value of the cSubOpcionPuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCSubOpcionPuesto(Integer value) {
        this.cSubOpcionPuesto = value;
    }

    /**
     * Gets the value of the cTiempoEdoCivil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTiempoEdoCivil() {
        return cTiempoEdoCivil;
    }

    /**
     * Sets the value of the cTiempoEdoCivil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTiempoEdoCivil(String value) {
        this.cTiempoEdoCivil = value;
    }

    /**
     * Gets the value of the cTiempoRecide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTiempoRecide() {
        return cTiempoRecide;
    }

    /**
     * Sets the value of the cTiempoRecide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTiempoRecide(String value) {
        this.cTiempoRecide = value;
    }

    /**
     * Gets the value of the cTipoRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTipoRef() {
        return cTipoRef;
    }

    /**
     * Sets the value of the cTipoRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTipoRef(String value) {
        this.cTipoRef = value;
    }

}
