//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.08 at 12:13:00 PM GMT-06:00 
//


package bancoppel.cliente3.schema.TarjCop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import bancoppel.cliente3.schema.SpConsultaClienteseIndividual.CabeceraType;


/**
 * <p>Java class for TarjCopType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TarjCopType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pNumCte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PNumTarcoppel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="POption" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TarjCopType", propOrder = {
	"cabecera",
    "pNumCte",
    "pNumTarcoppel",
    "pOption"
})
public class TarjCopType {

	@XmlElement(required = true)
	protected CabeceraType cabecera;
    protected String pNumCte;
    @XmlElement(name = "PNumTarcoppel")
    protected String pNumTarcoppel;
    @XmlElement(name = "POption")
    protected Integer pOption;
    
    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link CabeceraType }
     *     
     */
    public CabeceraType getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabeceraType }
     *     
     */
    public void setCabecera(CabeceraType value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the pNumCte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNumCte() {
        return pNumCte;
    }

    /**
     * Sets the value of the pNumCte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNumCte(String value) {
        this.pNumCte = value;
    }

    /**
     * Gets the value of the pNumTarcoppel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNumTarcoppel() {
        return pNumTarcoppel;
    }

    /**
     * Sets the value of the pNumTarcoppel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNumTarcoppel(String value) {
        this.pNumTarcoppel = value;
    }

    /**
     * Gets the value of the pOption property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPOption() {
        return pOption;
    }

    /**
     * Sets the value of the pOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPOption(Integer value) {
        this.pOption = value;
    }

}
