//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.11 at 05:01:57 PM CDT 
//


package bancoppel.cliente3.schema.SpConsPeriocidad;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import bancoppel.cliente3.schema.SpConsultaClienteseIndividual.CabeceraType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bancoppel.cliente3.schema.SpConsPeriocidad package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SpConsPeriocidad_QNAME = new QName("http://www.bancoppel.com/Cliente3/SpConsPeriocidad/", "SpConsPeriocidad");
    private final static QName _SpConsPeriocidadResponse_QNAME = new QName("http://www.bancoppel.com/Cliente3/SpConsPeriocidad/", "SpConsPeriocidadResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bancoppel.cliente3.schema.SpConsPeriocidad
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpConsPeriocidadType }
     * 
     */
    public SpConsPeriocidadType createSpConsPeriocidadType() {
        return new SpConsPeriocidadType();
    }

    /**
     * Create an instance of {@link SpConsPeriocidadResponseType }
     * 
     */
    public SpConsPeriocidadResponseType createSpConsPeriocidadResponseType() {
        return new SpConsPeriocidadResponseType();
    }

    /**
     * Create an instance of {@link SpConsPeriocidadRegistroType }
     * 
     */
    public SpConsPeriocidadRegistroType createSpConsPeriocidadRegistroType() {
        return new SpConsPeriocidadRegistroType();
    }
    
    /**
     * Create an instance of {@link CabeceraType }
     * 
     */
    public CabeceraType createCabeceraType() {
        return new CabeceraType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpConsPeriocidadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bancoppel.com/Cliente3/SpConsPeriocidad/", name = "SpConsPeriocidad")
    public JAXBElement<SpConsPeriocidadType> createSpConsPeriocidad(SpConsPeriocidadType value) {
        return new JAXBElement<SpConsPeriocidadType>(_SpConsPeriocidad_QNAME, SpConsPeriocidadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpConsPeriocidadResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bancoppel.com/Cliente3/SpConsPeriocidad/", name = "SpConsPeriocidadResponse")
    public JAXBElement<SpConsPeriocidadResponseType> createSpConsPeriocidadResponse(SpConsPeriocidadResponseType value) {
        return new JAXBElement<SpConsPeriocidadResponseType>(_SpConsPeriocidadResponse_QNAME, SpConsPeriocidadResponseType.class, null, value);
    }

}
