//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.11 at 05:01:57 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bancoppel.com/Cliente3/SpConsPeriocidad/")
package bancoppel.cliente3.schema.SpConsPeriocidad;
