//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.11 at 05:01:57 PM CDT 
//


package bancoppel.cliente3.schema.SpConsPeriocidad;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import bancoppel.cliente3.schema.SpConsultaClienteseIndividual.CabeceraType;


/**
 * <p>Java class for SpConsPeriocidadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsPeriocidadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pEmpresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pNumSol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsPeriocidadType", propOrder = {
	"cabecera",	
    "pEmpresa",
    "pNumSol"
})
public class SpConsPeriocidadType {
	@XmlElement(required = true)
	protected CabeceraType cabecera;
    protected String pEmpresa;
    protected String pNumSol;

    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link CabeceraType }
     *     
     */
    public CabeceraType getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabeceraType }
     *     
     */
    public void setCabecera(CabeceraType value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the pEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEmpresa() {
        return pEmpresa;
    }

    /**
     * Sets the value of the pEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEmpresa(String value) {
        this.pEmpresa = value;
    }

    /**
     * Gets the value of the pNumSol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNumSol() {
        return pNumSol;
    }

    /**
     * Sets the value of the pNumSol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNumSol(String value) {
        this.pNumSol = value;
    }

}
