//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.11 at 05:01:57 PM CDT 
//


package bancoppel.cliente3.schema.SpConsPeriocidad;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpConsPeriocidadRegistroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsPeriocidadRegistroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cCodigo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idPeriodicidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cPeriodicidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cDesPeriocidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsPeriocidadRegistroType", propOrder = {
    "cCodigo",
    "idPeriodicidad",
    "cPeriodicidad",
    "cDesPeriocidad"
})
public class SpConsPeriocidadRegistroType {

    protected String cCodigo;
    protected String idPeriodicidad;
    protected String cPeriodicidad;
    protected String cDesPeriocidad;

    /**
     * Gets the value of the cCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCodigo() {
        return cCodigo;
    }

    /**
     * Sets the value of the cCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCodigo(String value) {
        this.cCodigo = value;
    }

    /**
     * Gets the value of the idPeriodicidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPeriodicidad() {
        return idPeriodicidad;
    }

    /**
     * Sets the value of the idPeriodicidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPeriodicidad(String value) {
        this.idPeriodicidad = value;
    }

    /**
     * Gets the value of the cPeriodicidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPeriodicidad() {
        return cPeriodicidad;
    }

    /**
     * Sets the value of the cPeriodicidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPeriodicidad(String value) {
        this.cPeriodicidad = value;
    }

    /**
     * Gets the value of the cDesPeriocidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDesPeriocidad() {
        return cDesPeriocidad;
    }

    /**
     * Sets the value of the cDesPeriocidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDesPeriocidad(String value) {
        this.cDesPeriocidad = value;
    }

}
