//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 09:13:47 AM MDT 
//


package bancoppel.cliente3.schema.SpConsultaClienteseIndividual;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bancoppel.cliente3.schema.SpConsultaClienteseIndividual package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SpConsultaClienteseIndividual_QNAME = new QName("http://www.bancoppel.com/Cliente3/SpConsultaClienteseIndividual/", "SpConsultaClienteseIndividual");
    private final static QName _SpConsultaClienteseIndividualResponse_QNAME = new QName("http://www.bancoppel.com/Cliente3/SpConsultaClienteseIndividual/", "SpConsultaClienteseIndividualResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bancoppel.cliente3.schema.SpConsultaClienteseIndividual
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpConsultaClienteseIndividualType }
     * 
     */
    public SpConsultaClienteseIndividualType createSpConsultaClienteseIndividualType() {
        return new SpConsultaClienteseIndividualType();
    }

    /**
     * Create an instance of {@link SpConsultaClienteseIndividualResponseType }
     * 
     */
    public SpConsultaClienteseIndividualResponseType createSpConsultaClienteseIndividualResponseType() {
        return new SpConsultaClienteseIndividualResponseType();
    }

    /**
     * Create an instance of {@link SpConsultaClienteseIndividualRegistroType }
     * 
     */
    public SpConsultaClienteseIndividualRegistroType createSpConsultaClienteseIndividualRegistroType() {
        return new SpConsultaClienteseIndividualRegistroType();
    }

    /**
     * Create an instance of {@link CabeceraType }
     * 
     */
    public CabeceraType createCabeceraType() {
        return new CabeceraType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpConsultaClienteseIndividualType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bancoppel.com/Cliente3/SpConsultaClienteseIndividual/", name = "SpConsultaClienteseIndividual")
    public JAXBElement<SpConsultaClienteseIndividualType> createSpConsultaClienteseIndividual(SpConsultaClienteseIndividualType value) {
        return new JAXBElement<SpConsultaClienteseIndividualType>(_SpConsultaClienteseIndividual_QNAME, SpConsultaClienteseIndividualType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpConsultaClienteseIndividualResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bancoppel.com/Cliente3/SpConsultaClienteseIndividual/", name = "SpConsultaClienteseIndividualResponse")
    public JAXBElement<SpConsultaClienteseIndividualResponseType> createSpConsultaClienteseIndividualResponse(SpConsultaClienteseIndividualResponseType value) {
        return new JAXBElement<SpConsultaClienteseIndividualResponseType>(_SpConsultaClienteseIndividualResponse_QNAME, SpConsultaClienteseIndividualResponseType.class, null, value);
    }

}
