//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 09:13:47 AM MDT 
//


package bancoppel.cliente3.schema.SpConsultaClienteseIndividual;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpConsultaClienteseIndividualType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsultaClienteseIndividualType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cabecera" type="{http://www.bancoppel.com/Logger}CabeceraType"/>
 *         &lt;element name="pEmpresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pNumCte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pTipoBusqueda" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsultaClienteseIndividualType", propOrder = {
    "cabecera",
    "pEmpresa",
    "pNumCte",
    "pTipoBusqueda"
})
public class SpConsultaClienteseIndividualType {

    @XmlElement(required = true)
    protected CabeceraType cabecera;
    protected String pEmpresa;
    protected String pNumCte;
    protected Integer pTipoBusqueda;

    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link CabeceraType }
     *     
     */
    public CabeceraType getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabeceraType }
     *     
     */
    public void setCabecera(CabeceraType value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the pEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEmpresa() {
        return pEmpresa;
    }

    /**
     * Sets the value of the pEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEmpresa(String value) {
        this.pEmpresa = value;
    }

    /**
     * Gets the value of the pNumCte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNumCte() {
        return pNumCte;
    }

    /**
     * Sets the value of the pNumCte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNumCte(String value) {
        this.pNumCte = value;
    }

    /**
     * Gets the value of the pTipoBusqueda property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPTipoBusqueda() {
        return pTipoBusqueda;
    }

    /**
     * Sets the value of the pTipoBusqueda property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPTipoBusqueda(Integer value) {
        this.pTipoBusqueda = value;
    }

}
