//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 09:13:47 AM MDT 
//


package bancoppel.cliente3.schema.SpConsultaClienteseIndividual;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpConsultaClienteseIndividualRegistroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsultaClienteseIndividualRegistroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vCodRet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vNumCredConslt1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vNumTarjeta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vSE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vCausa" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="vDescripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vFechaMod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsultaClienteseIndividualRegistroType", propOrder = {
    "vCodRet",
    "vNumCredConslt1",
    "vNumTarjeta",
    "vse",
    "vCausa",
    "vDescripcion",
    "vFechaMod"
})
public class SpConsultaClienteseIndividualRegistroType {

    protected String vCodRet;
    protected String vNumCredConslt1;
    protected String vNumTarjeta;
    @XmlElement(name = "vSE")
    protected String vse;
    protected Integer vCausa;
    protected String vDescripcion;
    protected String vFechaMod;

    /**
     * Gets the value of the vCodRet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVCodRet() {
        return vCodRet;
    }

    /**
     * Sets the value of the vCodRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVCodRet(String value) {
        this.vCodRet = value;
    }

    /**
     * Gets the value of the vNumCredConslt1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVNumCredConslt1() {
        return vNumCredConslt1;
    }

    /**
     * Sets the value of the vNumCredConslt1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVNumCredConslt1(String value) {
        this.vNumCredConslt1 = value;
    }

    /**
     * Gets the value of the vNumTarjeta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVNumTarjeta() {
        return vNumTarjeta;
    }

    /**
     * Sets the value of the vNumTarjeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVNumTarjeta(String value) {
        this.vNumTarjeta = value;
    }

    /**
     * Gets the value of the vse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSE() {
        return vse;
    }

    /**
     * Sets the value of the vse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSE(String value) {
        this.vse = value;
    }

    /**
     * Gets the value of the vCausa property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVCausa() {
        return vCausa;
    }

    /**
     * Sets the value of the vCausa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVCausa(Integer value) {
        this.vCausa = value;
    }

    /**
     * Gets the value of the vDescripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVDescripcion() {
        return vDescripcion;
    }

    /**
     * Sets the value of the vDescripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVDescripcion(String value) {
        this.vDescripcion = value;
    }

    /**
     * Gets the value of the vFechaMod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVFechaMod() {
        return vFechaMod;
    }

    /**
     * Sets the value of the vFechaMod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVFechaMod(String value) {
        this.vFechaMod = value;
    }

}
