//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.21 at 05:27:11 PM GMT-06:00 
//


package bancoppel.cliente3.schema.SpConsultaVencidoBancoppel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpConsultaVencidoBancoppelRegistroType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsultaVencidoBancoppelRegistroType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sCodRet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sMensaje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sNumeroCliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sIdVencido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sIdSaturacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsultaVencidoBancoppelRegistroType", propOrder = {
    "sCodRet",
    "sMensaje",
    "sNumeroCliente",
    "sIdVencido",
    "sIdSaturacion"
})
public class SpConsultaVencidoBancoppelRegistroType {

    protected String sCodRet;
    protected String sMensaje;
    protected String sNumeroCliente;
    protected String sIdVencido;
    protected String sIdSaturacion;

    /**
     * Gets the value of the sCodRet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCodRet() {
        return sCodRet;
    }

    /**
     * Sets the value of the sCodRet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCodRet(String value) {
        this.sCodRet = value;
    }

    /**
     * Gets the value of the sMensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMensaje() {
        return sMensaje;
    }

    /**
     * Sets the value of the sMensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMensaje(String value) {
        this.sMensaje = value;
    }

    /**
     * Gets the value of the sNumeroCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNumeroCliente() {
        return sNumeroCliente;
    }

    /**
     * Sets the value of the sNumeroCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNumeroCliente(String value) {
        this.sNumeroCliente = value;
    }

    /**
     * Gets the value of the sIdVencido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIdVencido() {
        return sIdVencido;
    }

    /**
     * Sets the value of the sIdVencido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIdVencido(String value) {
        this.sIdVencido = value;
    }

    /**
     * Gets the value of the sIdSaturacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIdSaturacion() {
        return sIdSaturacion;
    }

    /**
     * Sets the value of the sIdSaturacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIdSaturacion(String value) {
        this.sIdSaturacion = value;
    }

}
