//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.21 at 05:27:11 PM GMT-06:00 
//


package bancoppel.cliente3.schema.SpConsultaVencidoBancoppel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import bancoppel.cliente3.schema.SpConsultaDatosCteCoppel.CabeceraType;


/**
 * <p>Java class for SpConsultaVencidoBancoppelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpConsultaVencidoBancoppelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pNumCliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pTipoCliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gen1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gen2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gen3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpConsultaVencidoBancoppelType", propOrder = {
	"cabecera",	
    "pNumCliente",
    "pTipoCliente",
    "gen1",
    "gen2",
    "gen3"
})
public class SpConsultaVencidoBancoppelType {

	@XmlElement(required = true)
    protected CabeceraType cabecera;
    protected String pNumCliente;
    protected String pTipoCliente;
    protected String gen1;
    protected String gen2;
    protected String gen3;
    
    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link CabeceraType }
     *     
     */
    public CabeceraType getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabeceraType }
     *     
     */
    public void setCabecera(CabeceraType value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the pNumCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNumCliente() {
        return pNumCliente;
    }

    /**
     * Sets the value of the pNumCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNumCliente(String value) {
        this.pNumCliente = value;
    }

    /**
     * Gets the value of the pTipoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPTipoCliente() {
        return pTipoCliente;
    }

    /**
     * Sets the value of the pTipoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPTipoCliente(String value) {
        this.pTipoCliente = value;
    }

    /**
     * Gets the value of the gen1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGen1() {
        return gen1;
    }

    /**
     * Sets the value of the gen1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGen1(String value) {
        this.gen1 = value;
    }

    /**
     * Gets the value of the gen2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGen2() {
        return gen2;
    }

    /**
     * Sets the value of the gen2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGen2(String value) {
        this.gen2 = value;
    }

    /**
     * Gets the value of the gen3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGen3() {
        return gen3;
    }

    /**
     * Sets the value of the gen3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGen3(String value) {
        this.gen3 = value;
    }

}
